import type { BasicSignClass, VerifiedSignDefinition } from './signCollectionTypes';

export const VERIFIED_SIGN_DEFINITIONS: Record<BasicSignClass, VerifiedSignDefinition> = {
  water: {
    id: 'water',
    englishLabel: 'Water',
    urduLabel: 'پانی',
    conceptDescription: 'Asking for drinking water / expressing thirst',
    pslSource: 'FESF Pakistan Sign Language Literacy Project & SignSpeak V1/V2 dataset',
    existingV1Dataset: true,
    existingV2Dataset: true,
    gestureReferenceAvailable: true,
    safeToCollect: true,
    gestureInstructions: 'Dominant hand cups or forms W/fingers, moves towards or touches chin/mouth.',
    urduInstructions: 'ہاتھ کو پانی پینے کے انداز میں منہ یا ٹھوڑی کی طرف لائیں۔',
    targetCount: 30,
  },
  help: {
    id: 'help',
    englishLabel: 'Help',
    urduLabel: 'مدد',
    conceptDescription: 'Requesting urgent or general assistance',
    pslSource: 'FESF Pakistan Sign Language Literacy Project & SignSpeak V2 dataset',
    existingV1Dataset: false,
    existingV2Dataset: true,
    gestureReferenceAvailable: true,
    safeToCollect: true,
    gestureInstructions: 'Upright fist (thumbs-up) placed upon the flat open palm of the other hand, lifted upward together.',
    urduInstructions: 'ایک بند مٹھی کو دوسرے کھلے ہاتھ کی ہتھیلی پر رکھ کر اوپر کی طرف اٹھائیں۔',
    targetCount: 30,
  },
  hungry: {
    id: 'hungry',
    englishLabel: 'Hungry',
    urduLabel: 'بھوک',
    conceptDescription: 'Expressing hunger or requesting food',
    pslSource: 'FESF Pakistan Sign Language Literacy Project & SignSpeak V2 dataset',
    existingV1Dataset: false,
    existingV2Dataset: true,
    gestureReferenceAvailable: true,
    safeToCollect: true,
    gestureInstructions: 'Flat hand placed against stomach/chest area and moved downward towards the abdomen.',
    urduInstructions: 'ہاتھ کو سینے یا پیٹ پر رکھ کر نیچے کی طرف حرکت دیں۔',
    targetCount: 30,
  },
  need: {
    id: 'need',
    englishLabel: 'Need',
    urduLabel: 'ضرورت',
    conceptDescription: 'Expressing necessity or urgent requirement',
    pslSource: 'FESF Pakistan Sign Language Literacy Project & SignSpeak V2 dataset',
    existingV1Dataset: false,
    existingV2Dataset: true,
    gestureReferenceAvailable: true,
    safeToCollect: true,
    gestureInstructions: 'Bent index finger (hook shape) moves firmly downward once or twice in front of body.',
    urduInstructions: 'شہادت کی انگلی کو موڑ کر سامنے کی طرف نیچے حرکت دیں۔',
    targetCount: 30,
  },
  want: {
    id: 'want',
    englishLabel: 'Want',
    urduLabel: 'چاہئے',
    conceptDescription: 'Expressing desire or preference',
    pslSource: 'FESF Pakistan Sign Language Literacy Project & SignSpeak V2 dataset',
    existingV1Dataset: false,
    existingV2Dataset: true,
    gestureReferenceAvailable: true,
    safeToCollect: true,
    gestureInstructions: 'Open hands facing upward with fingers slightly curved, pulled back toward chest/body.',
    urduInstructions: 'دونوں ہاتھوں کی ہتھیلیاں اوپر کی طرف رکھتے ہوئے سینے کی طرف کھینچیں۔',
    targetCount: 30,
  },
  hello: {
    id: 'hello',
    englishLabel: 'Hello / Salam',
    urduLabel: 'السلام علیکم / ہیلو',
    conceptDescription: 'Greeting someone',
    pslSource: 'FESF Pakistan Sign Language Literacy Project & SignSpeak V1/V2 dataset',
    existingV1Dataset: true,
    existingV2Dataset: true,
    gestureReferenceAvailable: true,
    safeToCollect: true,
    gestureInstructions: 'Open palm waves outward from forehead/temple area toward the recipient.',
    urduInstructions: 'ہاتھ کو ماتھے کے پاس سے سامنے کی طرف سلام کے انداز میں لہرائیں۔',
    targetCount: 30,
  },
  thankyou: {
    id: 'thankyou',
    englishLabel: 'Thank You',
    urduLabel: 'شکریہ',
    conceptDescription: 'Expressing appreciation and gratitude',
    pslSource: 'FESF Pakistan Sign Language Literacy Project & SignSpeak V1/V2 dataset',
    existingV1Dataset: true,
    existingV2Dataset: true,
    gestureReferenceAvailable: true,
    safeToCollect: true,
    gestureInstructions: 'Flat hand fingertips touch chin/lips, then move forward and outward toward person.',
    urduInstructions: 'سیدھے ہاتھ کی انگلیوں کو ٹھوڑی یا ہونٹوں پر چھو کر سامنے کی طرف بڑھائیں۔',
    targetCount: 30,
  },
  NO_SIGN: {
    id: 'NO_SIGN',
    englishLabel: 'No Sign / Neutral Background',
    urduLabel: 'کوئی اشارہ نہیں (غیر جانبدار)',
    conceptDescription: 'Negative baseline to prevent closed-set softmax false activations',
    pslSource: 'CommuniCare Negative Baseline (Essential Hard Negatives)',
    existingV1Dataset: false, // V1 only had all-zero "nothing"
    existingV2Dataset: false,
    gestureReferenceAvailable: true,
    safeToCollect: true,
    gestureInstructions: 'Natural non-sign motions: resting hands, open hands, touching face, adjusting glasses, entering/leaving frame, conversational fidgeting.',
    urduInstructions: 'عام حرکات: ہاتھ آرام کی حالت میں رکھنا، چہرے کو چھونا، عینک درست کرنا، ہاتھ فریم میں لانا یا لے جانا۔',
    targetCount: 50,
  },
};
